### PR TITLE
Linter: Spelling fixes

### PR DESCRIPTION
**Pull request by gbjk**
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run

### CODE REVIEW

**Review by thrasher- — APPROVED** [review]
Thank you!

**Review by shazbert — APPROVED** [review]
Changes ACK. Thanks.

**Review by gloriousCode — APPROVED** [review]
yjsml upi gpt goccomh yjpdr d[r;;omh oddird@

**Comment by thrasher-** [comment]
> yjsml upi gpt goccomh yjpdr d[r;;omh oddird@



> yjsml upi gpt goccomh yjpdr d[r;;omh oddird@

Linter: goccomh should be (gocomh) fixing instead of fixxing or perhaps that's intended 😆

**Pull request merged**
