### PR TITLE
Coinbene: Fix ticker pair parsing

### PR DESCRIPTION
**Pull request by thrasher-**
# PR Description

A new instruments method was introduced which allows us to use it instead of string indexing.

Fixes # (issue)

https://github.com/thrasher-corp/gocryptotrader/issues/662

- [X] Bug fix (non-breaking change which fixes an issue)

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Travis with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by MadCozBadd — APPROVED** [review]
tACK!!! no issues found!

**Review by gloriousCode — CHANGES_REQUESTED** [review]
Thank you for this! I appreciate Coinbene working again. I do have a request that's semi-related.

The coinbene.go function `SendAuthHTTPRequest` does not set the field `Endpoint:      f,` when making the request and so all authenticated requests are blocked and return the ratelimit error
`errors.New("rate limit error endpoint functionality not set")`. Once Endpoint is set, authenticated requests/tests work (though its currently under maintenance)

Would you be able to fix it while you're here? 😄

**Review by shazbert — APPROVED** [review]
tACK! 🦅

**Review by gloriousCode — APPROVED** [review]
tACK! Thanks for making that extra change 🎉

**Pull request merged**
