### PR TITLE
Binance: convert timestamps to time.Time

### PR DESCRIPTION
**Pull request by Rots**
* add custom Unmarshal function for JSON types

# PR Description

To make the Binance API easier to use we can already do the time conversions for the user of the library.

## Type of change

- [x] Improvement (non-breaking change that improves functionality)

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Travis with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by shazbert — APPROVED** [review]
tACK, looks good! Thanks.

**Review by MadCozBadd — APPROVED** [review]
wow. litearlly went through all ur json tags in type_convert.go and couldnt find a single mistake. tests work. no unmarshalling issues! tACK

**Review by gloriousCode — APPROVED** [review]
tACK! Nice work on this. It simplifies the constant inline conversions we've been doing 🤙

**Review by thrasher- — APPROVED** [review]
tACK, thanks @Rots !

**Pull request merged**
