### PR TITLE
docs: Migrate development tracking from Trello to GitHub Projects

### PR DESCRIPTION
**Pull request by thrasher-**
# PR Description

Swap Trello for Github Projects and updates docs. Also fixes minor doc issues like duplicate contributors, Codecov icon and subs tmpl missing sentences.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How has this been tested

- [x] Reading docs

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by shazbert — CHANGES_REQUESTED** [review]
Nice 👍 

image


Seems to be a few readmes that might have been missed nested in inconspicuous places. 👻 spooky.

**Comment by thrasher-** [comment]
Fixed the remaining ones and specific templates, though I skipped the apichecker tool since it's no longer valid

**Review by shazbert — APPROVED** [review]
Good stuff nothing further from me!

**Review by gloriousCode — CHANGES_REQUESTED** [review]
I reject this on the basis the GitHub Projects doesn't allow you to have a sweet lambo wallpaper

**Review by gloriousCode — APPROVED** [review]
Just kidding, tACK!

**Comment by thrasher-** [comment]
> I reject this on the basis the GitHub Projects doesn't allow you to have a sweet lambo wallpaper

This also made me very sad 😢 🕯️

**Pull request merged**
