### PR TITLE
fix 440: SubmitOrder and CB-ACCESS-TIMESTAMP value

### PR DESCRIPTION
**Pull request by Christian-Achilli**
Fixes # 440

## Type of change
Lowered order.Side when submitting an order to Coinbasepro
Change the CB-ACCESS-TIMESTAMP to time.Now() as the nonce that was used was giving unstable results, mostly failures

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested
By creating real limit orders using my personal account

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Travis with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Christian-Achilli** [comment]
Are you sure it is safe to remove `request.Item` from all of the exchanges? Happy to do that but I am not sure about the effects

**Comment by xtda** [comment]
> Are you sure it is safe to remove `request.Item` from all of the exchanges? Happy to do that but I am not sure about the effects

I believe he means from CoinBasePro only so remove it from here:

https://github.com/thrasher-corp/gocryptotrader/blob/17b6bdfa438ea020e45c73133304b22bf9c142e6/exchanges/coinbasepro/coinbasepro.go#L770

To disable CoinBasePro from locking and generating a nonce in SendPayLoad()

https://github.com/thrasher-corp/gocryptotrader/blob/17b6bdfa438ea020e45c73133304b22bf9c142e6/exchanges/request/request.go#L33

**Comment by thrasher-** [comment]
Thanks for the PR!

Do you mind pasting obfuscated logs of the timestamp issues of what happens on master? I tried on my macOS host with getting active orders and couldn't replicate it after 20 requests. Does it happen after a specific amount?

```
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Cb-Access-Timestamp]: [1581664690]
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request header [Cb-Access-Sign]: [sig]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Cb-Access-Sign]: [MXz6rOEKnN6Xq4Xq+JXahH/w1ehL+PmfWS/umfik8nY=]
CoinbasePro request header [Cb-Access-Timestamp]: [1581664691]
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Cb-Access-Sign]: [WPvEkKumTZVGChJ6vIkT3MmwgQWKYTCPWmz8qT0ORm4=]
CoinbasePro request header [Cb-Access-Timestamp]: [1581664692]
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request header [Cb-Access-Sign]: [RGnZ/1xnlL1zFO4dMyqx48Xvzwd331yGaedSyHbPh9Y=]
CoinbasePro request header [Cb-Access-Timestamp]: [1581664693]
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request header [Cb-Access-Sign]: [T6MuTa0PJMRgbl7mQDzILe64yfyuPBP35SCtk+jrnyQ=]
CoinbasePro request header [Cb-Access-Timestamp]: [1581664694]
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Cb-Access-Timestamp]: [1581664695]
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request header [Cb-Access-Sign]: [lRArsET9iOABCbR7WXgUAz2prH5y64r60vQOx6TrOBY=]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Cb-Access-Timestamp]: [1581664696]
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request header [Cb-Access-Sign]: [GsoGCU7UAbP1RpqYiPrHl3XqpMojzt2W3Wf/EMrssJI=]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request header [Cb-Access-Sign]: [G4yoL/as1e34NHwq9gaLxz8c5Yu0dEqNNsSxjeTZf+M=]
CoinbasePro request header [Cb-Access-Timestamp]: [1581664697]
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request header [Cb-Access-Sign]: [Np8+UcIoOV3QmI0GTFIO7UQ0n4fUQYbbWe0JNye2FBQ=]
CoinbasePro request header [Cb-Access-Timestamp]: [1581664698]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request header [Cb-Access-Sign]: [tf1jatePwUU/nCsH1gVadoXlnSleyfsLnvEy7wLeB1o=]
CoinbasePro request header [Cb-Access-Timestamp]: [1581664699]
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Cb-Access-Sign]: [c+KSdYQhAMNkCAgO0uGLp0YykXjVUJ7PzRGyRw82qRs=]
CoinbasePro request header [Cb-Access-Timestamp]: [1581664700]
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request header [Cb-Access-Sign]: [4kXxfTRJVKlwT+gazi30fCKW3MiQuwq5fApo1m98Eew=]
CoinbasePro request header [Cb-Access-Timestamp]: [1581664701]
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Cb-Access-Sign]: [hHy2G3Bf4PzF+UTasUUKlzH5rjyUzyveLQuRm2w0Jpk=]
CoinbasePro request header [Cb-Access-Timestamp]: [1581664702]
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Cb-Access-Sign]: [YkaEh2OQM/QBvIIZzoTGbs+kvAwnsK480a9H2FvCM3U=]
CoinbasePro request header [Cb-Access-Timestamp]: [1581664703]
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request header [Cb-Access-Sign]: [h3IocByPlAl+zlbm+B6s15xBcsxm8LKVv5VlyZnkoh0=]
CoinbasePro request header [Cb-Access-Timestamp]: [1581664704]
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request header [Cb-Access-Sign]: [2NvxaMC/riFayU1k/MItNMjW5LFhp8kKaMO6FRjf6cQ=]
CoinbasePro request header [Cb-Access-Timestamp]: [1581664705]
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request header [Cb-Access-Sign]: [pmthGdoCFE0X//4jWdmG7QNINbC/304Rb0MDEyZytmo=]
CoinbasePro request header [Cb-Access-Timestamp]: [1581664706]
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Cb-Access-Sign]: [4L1TCtL/3U00YlsgkJbLpyJ9lLkOv/Z83BDhGwXufe8=]
CoinbasePro request header [Cb-Access-Timestamp]: [1581664707]
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request header [Cb-Access-Sign]: [nuQP/seaSD+vzUSysxnFKmo0A3JgDia4lofvnfUvehs=]
CoinbasePro request header [Cb-Access-Timestamp]: [1581664708]
CoinbasePro request type: GET
CoinbasePro request body: 
CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=LTC-BTC&status=open&status=pending&status=active
CoinbasePro request header [Cb-Access-Timestamp]: [1581664709]
CoinbasePro request header [Cb-Access-Key]: [key]
CoinbasePro request header [Cb-Access-Passphrase]: [passerino]
CoinbasePro request header [Content-Type]: [application/json]
CoinbasePro request header [Cb-Access-Sign]: [1IanapBQfwagpuKi+humBK+kzNYkZZO3BSTH/0IQKVs=]
CoinbasePro request type: GET
CoinbasePro request body: 
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
HTTP status: 200 OK, Code: 200
CoinbasePro raw response: []
```

**Comment by Christian-Achilli** [comment]
How can I generate the same log as you? I enabled `verbose` for Coinbasepro but I am flooded by `l2` WebSocket messages

**Comment by Christian-Achilli** [comment]
I tried GetActiveOrders on master and getting the same error.=== RUN   TestGetActiveOrders
```
--- FAIL: TestGetActiveOrders (0.14s)
    gocryptotrader_test.go:26: rpc error: code = Unknown desc = CoinbasePro unsuccessful HTTP status code: 400  raw response: {"message":"request timestamp expired"}
FAIL
```

Test code
```
func TestGetActiveOrders(t *testing.T) {
	err := GetActiveOrders("coinbasepro", "spot", "BTC-EUR", "-")
	if err != nil {
		t.Error(err)
	}
}
```
GTC client on my bot
```
func GetActiveOrders(exchangeName, assetType, currencyPair, delimiter string) error {
	conn, err := SetupClient()
	if err != nil {
		return err
	}
	defer conn.Close()
	cp := strings.Split(currencyPair, delimiter)
	client := gctrpc.NewGoCryptoTraderClient(conn)
	result, err := client.GetOrders(context.Background(), &gctrpc.GetOrdersRequest{
		Exchange:  exchangeName,
		AssetType: assetType,
		Pair: &gctrpc.CurrencyPair{
			Delimiter: delimiter,
			Base:      cp[0],
			Quote:     cp[1],
		},
	})
	if err != nil {
		return err
	}

	jsonOutput(result)
	return nil
}
```

**Comment by thrasher-** [comment]
Please rebase this, then it LGTM. The reason this is happening is because once the nonce is initialised, it is set the current time.Now().Unix() timestamp and incremented by 1 on every subsequent request. The issue is that if it has sent a request, but has made no requests for >= 30 seconds, on the next request the incorrect timestamp issue will be thrown because the timestamp is many seconds behind the servers, causing the incorrect timestamp issue

**Comment by Christian-Achilli** [comment]
rebased

**Comment by Christian-Achilli** [comment]
Hi @shazbert it should be ok now but please let me know otherwise. I had a conflict on go.sum and go.mod and 2 commits were skipped during rebase

> 24/02/2020
> 12:56	Rebase Successful
> 			Rebased fix/440
> 			The following commits were skipped during rebase:
> 			f68b59b3 Bump github.com/grpc-ecosystem/grpc-gateway from 1.12.2 to 1.13.0
> 			b247a7fa Bump github.com/d5/tengo/v2 from 2.0.2 to 2.0.4 (#449)

**Pull request merged**
