### PR TITLE
Okx: Add subscription configuration

### PR DESCRIPTION
**Pull request by gbjk**
Just adds configurable subscriptions

Will also replay on top of the #1420 

## Stacked Dependencies

- [x] #1579 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by shazbert — APPROVED** [review]
tACK! Thanks. 

Out of scope issue: Just highlighting that if the apikey fails check on startup it still generates auth subs 
```
handleSubscription [trades spot ALGO/USDC trades spot APE/USDC books spot ALGO/USDC books spot APE/USDC tickers spot ALGO/USDC tickers spot APE/USDC account   orders spot ]
```
Then it has this error:
```
[ERROR] | WEBSOCKET | 28/08/2024 09:32:53 | subscription failure: Okx websocket connection: cannot send message to a disconnected websocket
```

This is happening on master as well.

**Comment by gbjk** [comment]
> Out of scope issue: Just highlighting that if the apikey fails check on startup it still generates auth subs

Think we leave that alone in lieu of #1420 being merged and then revisit

**Review by gloriousCode — APPROVED** [review]
tACK

**Comment by gbjk** [comment]
Rebased

**Review by thrasher- — APPROVED** [review]
image

All working as expected. tACK! 👍

**Pull request merged**
