### PR TITLE
Update docs/ADD_NEW_EXCHANGE.md documentation command for usage outside its tool dir

### PR DESCRIPTION
**Pull request by azhang**
previous cmd would fail

# PR Description

Please include a summary of the change, feature or issue which this pull request addresses. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Travis with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by xtda** [comment]
I don't agree with this change  it doesn't follow the standard we have set for other usage and other parts of the read me for example in this very same readme we have  

```sh
cd gocryptotrader/cmd/exchange_template
go run exchange_template.go -name FTX -ws -rest
```

all tools within the cmd folder run under the default assumption that you are executing it are within the path itself (e.g ~/gocryptotrader/cmd/documentation) and flags being an override 

If it needs to be documented then it should show users the default and also how to use the override not default to the override

**Comment by azhang** [comment]
@xtda hmm that sounds logical, however, the original command was not working for me -

```
❯❯❯ cd cmd/documentation
❯❯❯ go run documentation.go
Please set documentation tool directory via the tooldir flag if working outside of tool directory
exit status 1
```

**Comment by xtda** [comment]
> @xtda hmm that sounds logical, however, the original command was not working for me. @gloriousCode to answer your earlier question, here is the error I receive -
> 
> ```
> ❯❯❯ cd cmd/documentation
> ❯❯❯ go run documentation.go
> Please set documentation tool directory via the tooldir flag if working outside of tool directory
> exit status 1
> ```
> 
> I am on mac/zsh

interesting I am also on macos and using zsh so this might highlight other issues 

Can you prinf wd and comment the output if you get time?

https://github.com/thrasher-corp/gocryptotrader/blob/master/cmd/documentation/documentation.go#L117

**Comment by azhang** [comment]
@xtda here's the output if I println wd

```
❯❯❯ cd cmd/documentation 
❯❯❯ go run documentation.go
/Users/allie/src/gocryptotrader/cmd/documentation
Please set documentation tool directory via the tooldir flag if working outside of tool directory
exit status 1
```

**Comment by xtda** [comment]
> @xtda here's the output if I println wd
> 
> ```
> ❯❯❯ cd cmd/documentation 
> ❯❯❯ go run documentation.go
> /Users/allie/src/gocryptotrader/cmd/documentation
> Please set documentation tool directory via the tooldir flag if working outside of tool directory
> exit status 1
> ```

So its picking up the working directory but failing else where.

If you are happy to do more testing is there any chance you can 

```
	fmt.Println(filepath.Join(ref...))
	fmt.Println(strings.Contains(wd, filepath.Join(ref...)))
```

and post the result?

I am happy to have the README updated to explain the usage of tooldir flag as a default If its not fully cross platform compatible I am surprised nobody has run into the issue before.

**Comment by thrasher-** [comment]
> I don't agree with this change it doesn't follow the standard we have set for other usage and other parts of the read me for example in this very same readme we have
> 
> ```shell
> cd gocryptotrader/cmd/exchange_template
> go run exchange_template.go -name FTX -ws -rest
> ```
> 
> all tools within the cmd folder run under the default assumption that you are executing it are within the path itself (e.g ~/gocryptotrader/cmd/documentation) and flags being an override
> 
> If it needs to be documented then it should show users the default and also how to use the override not default to the override

With the goal of keeping this consistent based on our other cmd tools, I agree with @xtda . Since this has been stale for over a month, I will close this now but when you're free please paste the output in a new issue so we can attempt to troubleshoot the filepath issue.

**Pull request closed without merging**
