### PR TITLE
Go exchange

### PR DESCRIPTION
**Pull request by idoall**
# Description

Add Huobi and Binance Get Kline Func

### CODE REVIEW

**Comment by thrasher-** [comment]
Thanks for this PR @idoall ! In it's current state, it changes a lot of import paths so this will have to be adjusted. If you're unable to do this, I can look into these changes once engine branch has been merged into master (https://github.com/thrasher-corp/gocryptotrader/pull/382)

**Comment by thrasher-** [comment]
@idoall you can see a cleaned version of your changes in this branch: https://github.com/thrasher-corp/gocryptotrader/compare/idoall_progress#files_bucket

There still exists a few issues (merge conflict diff text like this: https://github.com/thrasher-corp/gocryptotrader/compare/idoall_progress#diff-e96a00b889f6ded9b51cccb30981e9a0R14) and commented code

**Comment by idoall** [comment]
> @idoall you can see a cleaned version of your changes in this branch: https://github.com/thrasher-corp/gocryptotrader/compare/idoall_progress#files_bucket
> 
> There still exists a few issues (merge conflict diff text like this: https://github.com/thrasher-corp/gocryptotrader/compare/idoall_progress#diff-e96a00b889f6ded9b51cccb30981e9a0R14) and commented code
OK, history has changed a lot. The latest version has begun to approach the master

**Comment by thrasher-** [comment]
Closed as there's a separate branch for this in https://github.com/thrasher-corp/gocryptotrader/compare/idoall_progress#files_bucket

**Pull request closed without merging**
