### PR TITLE
Kraken: Fix WS new order pair symbol format

### PR DESCRIPTION
**Pull request by gbjk**
- [x] Bug fix (non-breaking change which fixes an issue)

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run

### CODE REVIEW

**Review by gloriousCode — APPROVED** [review]
tACK!
image

**Comment by gbjk** [comment]
```
[ERROR] | WEBSOCKET | 27/07/2023 16:09:31 | 'PENDING' unrecognised order status Exchange Kraken: OrderID: ORDJGL-4OXRF-7JLPMW classification error: 'PENDING' unrecognised order status
[ERROR] | WEBSOCKET | 27/07/2023 16:09:31 | 'SELL' unrecognised order type Exchange Kraken: OrderID: ORDJGL-4OXRF-7JLPMW classification error: 'SELL' unrecognised order type
```

**Comment by gloriousCode** [comment]
I also got
```[DEBUG] | WEBSOCKET | 28/07/2023 10:04:10 | New Order: Kraken   NEW UNKNOWN UNKNOWN OrderID:OHY7OC-XCV6G-4ZZV35 ClientOrderID: Price:0.000000 Amount:0.000000 Executed Amount:0.000000 Remaining Amount:0.000000```
However, I took being able to place an order to be the important part instead of holding it up to fix a seperate bug

**Comment by gbjk** [comment]
Yep. In either case this fix is valid.
Wonder if another rebase might be needed for me. Only rebased yesterday though!

**Comment by gbjk** [comment]
Nope. Still an issue on master. Still need to fix the SELL classification issue too.

**Review by thrasher- — APPROVED** [review]

**Review by shazbert — APPROVED** [review]
tACK: 
image

**Pull request merged**
