### PR TITLE
Coinbase: Fix path issue for GetFills and GetOrders

### PR DESCRIPTION
**Pull request by thrasher-**
# PR Description

Fixes Coinbase GetFills/GetOrders issue as identified by whiskeywhiskey in Slack. I don't have any API keys for Coinbase, but the tests now show a correct path.

Fixes # (issue)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Travis with my changes
- [N/A] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by gloriousCode — APPROVED** [review]
tACK! I can confirm that the solution fixes the issues on GetFills and GetOrders. No longer returns "route not found" errors and instead returns 200's.
Only thing of minor note is that for the test `TestGetOrderHistory` (which calls GetOrders), the supplied currency (BTC LTC) is not supported on coinbasepro and _could_ be changed to BTC-USD

**Review by gloriousCode — APPROVED** [review]
Thanks for making those changes! reACK!

**Review by shazbert — APPROVED** [review]
tACK - Dont have keys for coinbase, but tested pathing:
`CoinbasePro request path: https://api.pro.coinbase.com/orders?product_id=BTC-USD&status=open&status=pending&status=active`

**Review by MadCozBadd — APPROVED** [review]
tACK!

**Pull request merged**
