### PR TITLE
gRPC: Uptime runtime to v2

### PR DESCRIPTION
**Pull request by thrasher-**
# PR Description

Updates gRPC runtime to version 2

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run
- [x] Running GCT and executing commands via gctcli

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Travis with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by shazbert — APPROVED** [review]
tACK! Updated and checked regeneration and utilisation of RPC via cli.

**Review by gloriousCode — APPROVED** [review]
tACK! Regenerated using WSL, Windows.bat, checked documentation. Tested against cli and REST endpoint

**Review by MadCozBadd — APPROVED** [review]
Works! tACK

**Review by shazbert — APPROVED** [review]
re-tACK - 🥇

**Review by MadCozBadd — APPROVED** [review]
reTACK

**Review by gloriousCode — APPROVED** [review]
Retested. tACK!

**Pull request merged**
