### PR TITLE
Tests: Fix fail on vendored modules

### PR DESCRIPTION
**Pull request by gbjk**
This fixes looking for LICENSE files in the vendor directory

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run

### CODE REVIEW

**Review by gloriousCode — APPROVED** [review]
tACK!
`go mod vendor`
before:
```
found an unexpected LICENSE file in a sub-directory: /Users/POPWIF/go/src/github.com/thrasher-corp/gocryptotrader/vendor/dario.cat/mergo/LICENSE
```
after:
```
ok  	github.com/thrasher-corp/gocryptotrader/internal/testing/utils	0.293s
```

**Review by thrasher- — CHANGES_REQUESTED** [review]
Need to also include a fix for `web/`:

               Error:          Received unexpected error:
                                found an unexpected LICENSE file in a sub-directory: /src/github.com/thrasher-corp/gocryptotrader/web/node_modules/@adobe/css-tools/LICENSE
                Test:           TestRootPathFromCWD

**Comment by gbjk** [comment]
> Need to also include a fix for web/:

Fixed 61f654b2

Considered just respecting .gitignore, but way too much effort, especially given this case would be cascading and ignoring all of web is "the right thing to do".

Will merge down immediately

**Review by thrasher- — APPROVED** [review]
tACK, thanks for making those changes!

**Pull request merged**
