### PR TITLE
Kraken - fix bugs with wrong indexes

### PR DESCRIPTION
**Pull request by vazha**
# PR Description

Kraken methods UpdateOrderFromModify and UpdateOrderFromDetail had issues with wrong slice indexes which case an panic
(just a typo)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project

### CODE REVIEW

**Review by MadCozBadd — APPROVED** [review]
tACK!

**Review by gloriousCode — APPROVED** [review]
WHOOPS 👀  Thank you for the PR and fixing my fat-finger coding. tACK

**Review by shazbert — APPROVED** [review]
utACK - Thanks

**Review by thrasher- — APPROVED** [review]
Nice catch @vazha 😆

**Pull request merged**
