### PR TITLE
Backtester: Update flag typo

### PR DESCRIPTION
**Pull request by snussik**
# PR Description

The typo in flag -config**P**ath breaks running backtest.

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by gloriousCode — CHANGES_REQUESTED** [review]
Hi snussik, thank you for your contribution and fix! I do have a request though. We generate our readme's from template files. So that we don't accidentally overwrite your fix, are you able to also make the same modification to: `gocryptotrader\cmd\documentation\backtester_templates\backtester_config_configbuilder_readme.tmpl` ?

**Review by thrasher- — APPROVED** [review]
tACK, thank you @snussik !

**Review by gloriousCode — APPROVED** [review]
Thank you for making that change and thank you for your contribution! 🎈

**Review by shazbert — APPROVED** [review]
ACK. Thank you!

**Review by MadCozBadd — APPROVED** [review]
tACK!!! Thanks alot!!

**Pull request merged**
