### PR TITLE
Binance: Fix occassional race failure on TestWsOrderExecutionReport

### PR DESCRIPTION
**Pull request by gbjk**
Fixes:
```
binance_test.go:2608: expected type order.Detail, found *orderbook.Depth
```

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by gloriousCode — APPROVED** [review]
tACK!
I'm happy with the change. I've got a [gist here](https://gist.github.com/gloriousCode/c2081642f9c646bd8143e5e20370ac9a) which should prevent future problems and removes the mutex, but your change addressing things just fine

**Review by shazbert — APPROVED** [review]
ch ACK.

**Comment by gbjk** [comment]
> I've got a [gist here](https://gist.github.com/gloriousCode/c2081642f9c646bd8143e5e20370ac9a) which should prevent future problems and removes the mutex, but your change addressing things just fine

Thanks! I did wonder about where the other data came from, sniffed for other things consuming DataHandler, but didn't take it further.

Fixed c0f11540

**Review by shazbert — APPROVED** [review]
Ch ACK! Thanks!

**Review by thrasher- — APPROVED** [review]
Thank you @gbjk and @gloriousCode for the further enhancements!

**Pull request merged**
