### PR TITLE
bitfinex: fix potential panic caused by wrapper issues cmd

### PR DESCRIPTION
**Pull request by shazbert**
# PR Description

Adds empty pair check to reduce panic potential.

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by gloriousCode — COMMENTED** [review]
I have tested that this addresses a bitfinex casing issue. When does exchange_wrapper_issues send empty pairs? Or did you mean exchange_wrapper_coverage?

**Review by gloriousCode — CHANGES_REQUESTED** [review]
Found the source of the issue
`func disruptFormatting(p currency.Pair) (currency.Pair, error) {` in `main.go` for `exchange_wrapper_issues` it returns an empty pair if base OR quote is empty. So Bitfinex margin and marginfutures calls get disrupted. I think using your same if statement in bitfinex wrapper in `disruptFormatting` would be an appropriate fix

**Review by gloriousCode — APPROVED** [review]
# [tACK!](https://www.youtube.com/watch?v=3ojvjwH6yRU)

**Review by thrasher- — APPROVED** [review]
tACK

**Pull request merged**
