### PR TITLE
Binance: Fix UKlineData func

### PR DESCRIPTION
**Pull request by phieudu241**
# PR Description
Fix some issues for `exchanges/binance/binance_ufutures.go#UKlineData` function
1. `UKlineData` func introduce some wrong parameters which lead to wrong response
start_time -> startTime
end_time -> endTime

2. Incorrect supported interval list
`ufuturesKlineData          = "/fapi/v1/klines?"`
The endpoint for this func can support all intervals the list of `validFuturesIntervals`
uValidPeriods -> validFuturesIntervals

3. Make consistency for time format with others Kline fetching func (ex: GetSpotKline)
time.Unix() --> convert.TimeFromUnixTimestampFloat 

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by shazbert — CHANGES_REQUESTED** [review]
Thanks for opening this PR: Changes are spot on 🚀 . The only thing that needs to be fixed is the mock response for `TestUKlineData` in binance_test.go

Due to the params changing, the mock server cannot give the correct response. If you need help implementing that, let me know.

**Comment by phieudu241** [comment]
Hi @shazbert,
I updated the mock response for that and the test cases look OK now.

**Review by shazbert — APPROVED** [review]
Changes ACK! @phieudu241 awesome thanks for that!

**Review by gloriousCode — APPROVED** [review]
tACK! Nice work and thank you for your contribution @phieudu241 !!

**Review by thrasher- — APPROVED** [review]
tACK, thanks @phieudu241 for your first contribution! NOTE: This highlights further future issues with start and endTime params

**Pull request merged**
