### PR TITLE
binance: adjust outbound start and end time payload strings and update unix to milliseconds

### LINKED ISSUE #1038: The startTime and endTime must be millisecond on Binance query deposit list.
https://github.com/thrasher-corp/gocryptotrader/blob/293d6104ed38436d746a8c81c3b5428860131797/exchanges/binance/binance.go#L1011

### PR DESCRIPTION
**Pull request by shazbert**
# PR Description

`time.UTC().Unix()` -> `time.UTC().UnixMilli()`

ALSO: Sets correct outbound start and end time strings for USDT and coin margined futures

Fixes #1038

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [x] tested endpoint

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by gloriousCode — CHANGES_REQUESTED** [review]
Thanks for the quick fix. However, we have 67 total `.Unix()` in our implementation that can be changed and the API docs say: `All time and timestamp related fields are in milliseconds.`

**Review by thrasher- — APPROVED** [review]
tACK. No remanence of start_time, end_time, UnixNano's or Unix()

**Comment by thrasher-** [comment]
Will have to rescind that tACK for testing live, please apply this patch:

```
diff --git a/exchanges/binance/binance_live_test.go b/exchanges/binance/binance_live_test.go
index 5ea6bb72f..3fbea22fd 100644
--- a/exchanges/binance/binance_live_test.go
+++ b/exchanges/binance/binance_live_test.go
@@ -11,6 +11,7 @@ import (
 	"testing"
 
 	"github.com/thrasher-corp/gocryptotrader/config"
+	"github.com/thrasher-corp/gocryptotrader/exchanges/request"
 	"github.com/thrasher-corp/gocryptotrader/exchanges/sharedtestvalues"
 )
 
```

There also appears to be some other test issues

```
Binance processing websocket orderbook error fetching book already set to false for BTC-USDT spot
--- FAIL: TestGetHistoricalTrades (0.00s)
    binance_test.go:1284: Binance GetHistoricalTrades() error: Binance credentials are empty
--- FAIL: TestUTakerBuySellVol (0.19s)
    binance_test.go:394: Binance unsuccessful HTTP status code: 400 raw response: {"msg":"parameter 'startTime' is invalid.","code":-1130}
Binance failed to set exchange order execution limits. Err: cannot update exchange execution limits: unhandled asset type for exchange limits loading TRD_GRP_004
--- FAIL: TestGetFuturesTakerVolume (1.55s)
    binance_test.go:934: Binance unsuccessful HTTP status code: 400 raw response: {"msg":"parameter 'startTime' is invalid.","code":-1130}
--- FAIL: TestGetTraderFuturesPositionsRatio (1.69s)
    binance_test.go:910: Binance unsuccessful HTTP status code: 400 raw response: {"msg":"parameter 'startTime' is invalid.","code":-1130}
--- FAIL: TestGetTraderFuturesAccountRatio (1.80s)
    binance_test.go:898: Binance unsuccessful HTTP status code: 400 raw response: {"msg":"parameter 'startTime' is invalid.","code":-1130}
--- FAIL: TestUTopAcccountsLongShortRatio (1.98s)

    ```

**Review by gloriousCode — APPROVED** [review]
tACK! Tested without mock tests on all endpoints and its happy. Thanks for updating `binance.json` as well

That being said, if  you feel up to fixing more Binance on this PR, the function: `GetMarginMarkets` is ~a~ (broken) ~duplicate of `GetPerpMarkets` and can be removed.~

**Review by thrasher- — APPROVED** [review]
re-tACK, thanks for fixing those issues!

**Review by gloriousCode — APPROVED** [review]
tACK! Lovely improvements, thank you 🤩

**Pull request merged**
